service: aws-reto-softtek
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: dev
  region: us-east-1
  memorySize: 2048
  versionFunctions: false
  deploymentBucket:
    name: s3-sls-${self:provider.stage}
  logRetentionInDays: 1
  timeout: 60
  tracing:
    lambda: true
  environment:
    STAGE: ${self:provider.stage}
    SWAPI_BASE_URL: ${self:custom.SWAPI_URL}
    WEATHER_BASE_URL: ${self:custom.WEATHER_URL}
    WEATHER_API_KEY: ${self:custom.WEATHER_KEY}
    JWT_SECRET: ${self:custom.secreto_jwt}
    CACHE_TTL: 1800

package: 
  exclude:
    - '!node_modules/@vendia/**'
    - .serverless/**
    - .git/**
  include:
    - dist/**
    - node_modules/**

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
      - http:
          path: /
          method: ANY
    environment:
      DYNAMO_USERS_TABLE: ${self:service}-${self:provider.stage}-users
      DYNAMO_FUSION_TABLE: ${self:service}-${self:provider.stage}-fusion
      DYNAMO_CACHE_TABLE: ${self:service}-${self:provider.stage}-cache
 
plugins:
  - serverless-offline

custom:
  SWAPI_URL: https://swapi.py4e.com/api
  WEATHER_URL: https://api.openweathermap.org/data/2.5/weather
  WEATHER_KEY: 68a740e385965b46699c00876750e4c4
  secreto_jwt: api-softtek-rimac

resources:
  Resources:
    FusionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-fusion
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fusionId
            AttributeType: S
        KeySchema:
          - AttributeName: fusionId
            KeyType: HASH
      
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    CacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-cache
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: cacheId
            AttributeType: S
        KeySchema:
          - AttributeName: cacheId
            KeyType: HASH
