export const ErrorCodes = {
  // Errores de aplicación
  APP_INTERNAL_ERROR: 'APP_001',
  APP_CONFIG_ERROR: 'APP_002',
  APP_STARTUP_ERROR: 'APP_003',

  // Errores de base de datos
  DB_CONNECTION_ERROR: 'DB_001',
  DB_QUERY_ERROR: 'DB_002',
  DB_CONSTRAINT_VIOLATION: 'DB_003',
  DB_RECORD_NOT_FOUND: 'DB_004',
  DB_DUPLICATE_ENTRY: 'DB_005',
  DB_TIMEOUT: 'DB_006',

  // Errores de reglas de negocio
  BR_USER_ALREADY_EXISTS: 'BR_001',
  BR_INVALID_USER_STATUS: 'BR_002',
  BR_INSUFFICIENT_BALANCE: 'BR_003',
  BR_EXPIRED_TOKEN: 'BR_004',
  BR_INVALID_OPERATION: 'BR_005',

  // Errores de validación
  VAL_REQUIRED_FIELD: 'VAL_001',
  VAL_INVALID_FORMAT: 'VAL_002',
  VAL_INVALID_EMAIL: 'VAL_003',
  VAL_PASSWORD_TOO_WEAK: 'VAL_004',

  // Errores de autenticación
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_INVALID: 'AUTH_003',
  AUTH_USER_NOT_FOUND: 'AUTH_004',

  // Errores de autorización
  AUTHZ_INSUFFICIENT_PERMISSIONS: 'AUTHZ_001',
  AUTHZ_RESOURCE_FORBIDDEN: 'AUTHZ_002',
  AUTHZ_ROLE_NOT_AUTHORIZED: 'AUTHZ_003',

  // Errores de servicios externos
  EXT_SERVICE_UNAVAILABLE: 'EXT_001',
  EXT_SERVICE_TIMEOUT: 'EXT_002',
  EXT_API_RATE_LIMIT: 'EXT_003',
} as const;
